In [25]:
import pandas as pd

df = pd.read_csv('aerofit_treadmill_data.csv')
df

,Product,Age,Gender,Education,MaritalStatus,Usage,Fitness,Income,Miles
0,KP281,18,Male,14,Single,3,4,29562,112
1,KP281,19,Male,15,Single,2,3,31836,75
2,KP281,19,Female,14,Partnered,4,3,30699,66
3,KP281,19,Male,12,Single,3,3,32973,85
4,KP281,20,Male,13,Partnered,4,2,35247,47
...,...,...,...,...,...,...,...,...,...
175,KP781,40,Male,21,Single,6,5,83416,200
176,KP781,42,Male,18,Single,5,4,89641,200
177,KP781,45,Male,16,Single,5,5,90886,160
178,KP781,47,Male,18,Partnered,4,5,104581,120
179,KP781,48,Male,18,Partnered,4,5,95508,180

In [26]:
pd.crosstab(df['Product'], df['Gender'], normalize='index').round(3)*100

Gender   Female  Male
Product
KP281      50.0  50.0
KP481      48.3  51.7
KP781      17.5  82.5

> based on gender, KP781 is heavily skewed to Males;
> KP281 & KP 481 (cheaper versions) is equally popular

In [27]:
pd.crosstab(df['Product'], df['MaritalStatus'], normalize='index').round(3)*100

MaritalStatus  Partnered  Single
Product
KP281               60.0    40.0
KP481               60.0    40.0
KP781               57.5    42.5

> Partnered people are more likely to purchaese any product, as compared to singles

In [28]:
pd.crosstab(df['Product'], df['Fitness'], normalize='index').round(3)*100

Fitness    1     2     3     4     5
Product
KP281    1.2  17.5  67.5  11.2   2.5
KP481    1.7  20.0  65.0  13.3   0.0
KP781    0.0   0.0  10.0  17.5  72.5

> fitness level 3 people prefer cheaper versions - KP281, KP481 ; whereas the most expensive verioin is only popular among fitness level 5 people

In [29]:
df['Age_Group'] = pd.cut(df['Age'], bins=range(15, 65, 5), right=False, labels=[f'{i}-{i+4}' for i in range(15, 60, 5)])
print(df[['Age', 'Age_Group']].head())

pd.crosstab(df['Product'], df['Age_Group'], normalize='index').round(3)*100

   Age Age_Group
0   18     15-19
1   19     15-19
2   19     15-19
3   19     15-19
4   20     20-24

Age_Group  15-19  20-24  25-29  30-34  35-39  40-44  45-49  50-54
Product
KP281        5.0   28.8   32.5   12.5   12.5    5.0    2.5    1.2
KP481        1.7   26.7   26.7   25.0   11.7    5.0    3.3    0.0
KP781        0.0   25.0   42.5   15.0    5.0    5.0    7.5    0.0

> age groups 20-24, 25-29 are most avid purchasers; followed by age 30-34 ones

In [30]:
pd.crosstab(df['Product'], df['Education'], normalize='index').round(3)*100

Education   12   13    14   15    16    18   20   21
Product
KP281      2.5  3.8  37.5  5.0  48.8   2.5  0.0  0.0
KP481      1.7  3.3  38.3  1.7  51.7   3.3  0.0  0.0
KP781      0.0  0.0   5.0  0.0  37.5  47.5  2.5  7.5

> people with 14 years of education, are more likely to buy cheaper products KP281, KP481; people with 16 years of eduction are best targets for any type; and with 18 years of education are best for expenseive verisns KP781; beyond 18 not much use of targeting

In [31]:
pd.crosstab(df['Product'], df['Usage'], normalize='index').round(3)*100

Usage       2     3     4     5     6    7
Product
KP281    23.8  46.2  27.5   2.5   0.0  0.0
KP481    23.3  51.7  20.0   5.0   0.0  0.0
KP781     0.0   2.5  45.0  30.0  17.5  5.0

people with anticipated usage of 2-4 times a wekk are more likely to buy cheaper versions - KP281, KP481. whereas people who buy the expensive verison KP781 are mostly the ones who anticipate using 4-6 times a week

In [32]:
print(df['Income'].describe())

count       180.000000
mean      53719.577778
std       16506.684226
min       29562.000000
25%       44058.750000
50%       50596.500000
75%       58668.000000
max      104581.000000
Name: Income, dtype: float64

In [33]:
import numpy as np

# Based on the describe output, let's create custom bins
bins = [df['Income'].min(), 30000, 40000, 50000, 60000, 70000, 80000, df['Income'].max()]
labels = ['<30k', '30k-40k', '40k-50k', '50k-60k', '60k-70k', '70k-80k', '>80k']

df['Income_Group'] = pd.cut(df['Income'], bins=bins, labels=labels, right=False)
print(df[['Income', 'Income_Group']].head())

   Income Income_Group
0   29562         <30k
1   31836      30k-40k
2   30699      30k-40k
3   32973      30k-40k
4   35247      30k-40k

In [34]:
pd.crosstab(df['Product'], df['Income_Group'], normalize='index').round(3)*100

Income_Group  <30k  30k-40k  40k-50k  50k-60k  60k-70k  70k-80k  >80k
Product
KP281          1.2     27.5     31.2     32.5      7.5      0.0   0.0
KP481          0.0     15.0     35.0     38.3     11.7      0.0   0.0
KP781          0.0      0.0     13.2     15.8     15.8     10.5  44.7

people with incomes between 30k to 60k are more likely to spend on cheaper versions - KP281, KP481. whereas people with incomes 60k and abvoe are more likely to buy the expensive vrsion KP781

In [35]:
print(df['Miles'].describe())

count    180.000000
mean     103.194444
std       51.863605
min       21.000000
25%       66.000000
50%       94.000000
75%      114.750000
max      360.000000
Name: Miles, dtype: float64

In [36]:
# Based on the describe output, let's create custom bins for 'Miles'
bins = [df['Miles'].min(), 50, 100, 150, 200, df['Miles'].max() + 1] # Add +1 to max to ensure max value is included
labels = ['<50', '50-99', '100-149', '150-199', '>=200']

df['Miles_Group'] = pd.cut(df['Miles'], bins=bins, labels=labels, right=False)
print(df[['Miles', 'Miles_Group']].head())

   Miles Miles_Group
0    112     100-149
1     75       50-99
2     66       50-99
3     85       50-99
4     47         <50

In [37]:
pd.crosstab(df['Product'], df['Miles_Group'], normalize='index').round(3)*100

Miles_Group   <50  50-99  100-149  150-199  >=200
Product
KP281        15.0   62.5     20.0      2.5    0.0
KP481         8.3   65.0     21.7      3.3    1.7
KP781         0.0    2.5     30.0     40.0   27.5

people who expect to run from 50-150 miles a week are likely to buy cheaper verisons - KP281, KP481. people who buy expenseie verisona re usually the ones who expect to run 100-200 miles a week

ALL OBSERVATIONS:

1. based on gender, KP781 is heavily skewed to Males; KP281 & KP 481 (cheaper versions) is equally popular
2. Partnered people are more likely to purchaese any product, as compared to singles
3. fitness level 3 people prefer cheaper versions - KP281, KP481 ; whereas the most expensive verioin is only popular among fitness level 5 people
4. age groups 20-24, 25-29 are most avid purchasers; followed by age 30-34 ones
5. people with 14 years of education, are more likely to buy cheaper products KP281, KP481; people with 16 years of eduction are best targets for any type; and with 18 years of education are best for expenseive verisns KP781; beyond 18 not much use of targeting
6. people with anticipated usage of 2-4 times a wekk are more likely to buy cheaper versions - KP281, KP481. whereas people who buy the expensive verison KP781 are mostly the ones who anticipate using 4-6 times a week
7. people with incomes between 30k to 60k are more likely to spend on cheaper versions - KP281, KP481. whereas people with incomes 60k and abvoe are more likely to buy the expensive vrsion KP781
8. people who expect to run from 50-150 miles a week are likely to buy cheaper verisons - KP281, KP481. people who buy expenseie verisona re usually the ones who expect to run 100-200 miles a week



*   Overall there is a clear customer base for expensive version KP781 - males, partnered, fitness level 5, aged beween 20-29, with 16-18 years of eduction, who likely anticipate using 4-6 times a week and run 100-200 miles. And earn atleast 60k

* for other 2 cheaper verisons - KP281, KP481, there is no clear defined customer base, but we can still get an approx idea if the customer will buy based on their demographic profile and other factors

* this is only the analysis based on last 3 months of data, so need to take into account this might change over time as cusotmer preferences change